# Generated by Django 3.0.2 on 2020-02-15 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200215_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcatagory',
            new_name='subcategory',
        ),
    ]
